FORMAT: 1A
HOST: https://iot-temperature-scheduler.herokuapp.com/webapi

# iot-temperature-scheduler

temperature-scheduler is a simple API that allows users get the required schedule and set prefered one

## Ping [/ping]

### Ping service [GET]

Returns `200` if service is alive.

+ Response 200 (application/json)

## Schedule [/]

### Get Schedule [GET/houses/{house_id}/floors/{floor_id}/schedule?start=4&end=10]

Returns Schelude of the given time interval


+ Response 200 (application/json)
        
        [
            {
                "dateFrom": "yyyy-DD-MM HH:mm:ss",
                "dateTo": "yyyy-DD-MM HH:mm:ss",
                "temperature": 17
            }, {
                "dateFrom": "yyyy-DD-MM HH:mm:ss",
                "dateTo": "yyyy-DD-MM HH:mm:ss",
                "temperature": 21
            }
        ]
    
    

### Set Schedule [POST/houses/{house_id}/floors/{floor_id}]]
fo
Sets the given day's temperature schedule type to the prefered one

+ Request (application/json)

        {
            "dateFrom": "sunday,16:00",
            "dateTo": "sunday,22:00",
            "temperature": 18
        }

+ Response 200 (application/json)